UPDATE b_sm_product 
JOIN b_iblock_element 
SET b_sm_product.DNC_TYPE_CODE=1
WHERE 
	b_iblock_element.IBLOCK_SECTION_ID IN (SELECT BSE.IBLOCK_SECTION_ID
		FROM b_iblock_section_element BSE
		INNER JOIN b_iblock_section BSubS ON BSE.IBLOCK_SECTION_ID = BSubS.ID
		INNER JOIN b_iblock_section BS ON (BSubS.IBLOCK_ID=BS.IBLOCK_ID
			AND BSubS.LEFT_MARGIN>=BS.LEFT_MARGIN
			AND BSubS.RIGHT_MARGIN<=BS.RIGHT_MARGIN)
		WHERE BS.ID IN (81) AND BSubS.ID IN (83))
	AND b_iblock_element.ID=b_sm_product.PRODUCT_ID;

INSERT INTO b_sm_product (PRODUCT_ID, DNC_TYPE_CODE)
SELECT ID as PRODUCT_ID, 1 as DNC_TYPE_CODE
FROM b_iblock_element
WHERE 
	IBLOCK_SECTION_ID IN (SELECT BSE.IBLOCK_SECTION_ID
		FROM b_iblock_section_element BSE
		INNER JOIN b_iblock_section BSubS ON BSE.IBLOCK_SECTION_ID = BSubS.ID
		INNER JOIN b_iblock_section BS ON (BSubS.IBLOCK_ID=BS.IBLOCK_ID
			AND BSubS.LEFT_MARGIN>=BS.LEFT_MARGIN
			AND BSubS.RIGHT_MARGIN<=BS.RIGHT_MARGIN)
		WHERE BS.ID IN (81) AND BSubS.ID IN (83))
	AND ID NOT IN (SELECT b_sm_product.PRODUCT_ID FROM b_sm_product);


UPDATE b_sm_product 
JOIN b_iblock_element 
SET b_sm_product.DNC_TYPE_CODE=2
WHERE 
	b_iblock_element.IBLOCK_SECTION_ID IN (SELECT BSE.IBLOCK_SECTION_ID
		FROM b_iblock_section_element BSE
		INNER JOIN b_iblock_section BSubS ON BSE.IBLOCK_SECTION_ID = BSubS.ID
		INNER JOIN b_iblock_section BS ON (BSubS.IBLOCK_ID=BS.IBLOCK_ID
			AND BSubS.LEFT_MARGIN>=BS.LEFT_MARGIN
			AND BSubS.RIGHT_MARGIN<=BS.RIGHT_MARGIN)
		WHERE BS.ID IN (3) AND BSubS.ID IN (10))
	AND b_iblock_element.ID=b_sm_product.PRODUCT_ID;

INSERT INTO b_sm_product (PRODUCT_ID, DNC_TYPE_CODE)
SELECT ID as PRODUCT_ID, 2 as DNC_TYPE_CODE
FROM b_iblock_element
WHERE 
	IBLOCK_SECTION_ID IN (SELECT BSE.IBLOCK_SECTION_ID
		FROM b_iblock_section_element BSE
		INNER JOIN b_iblock_section BSubS ON BSE.IBLOCK_SECTION_ID = BSubS.ID
		INNER JOIN b_iblock_section BS ON (BSubS.IBLOCK_ID=BS.IBLOCK_ID
			AND BSubS.LEFT_MARGIN>=BS.LEFT_MARGIN
			AND BSubS.RIGHT_MARGIN<=BS.RIGHT_MARGIN)
		WHERE BS.ID IN (3) AND BSubS.ID IN (10))
	AND ID NOT IN (SELECT b_sm_product.PRODUCT_ID FROM b_sm_product);


UPDATE b_sm_product 
JOIN b_iblock_element 
SET b_sm_product.DNC_TYPE_CODE=3
WHERE 
	b_iblock_element.IBLOCK_SECTION_ID IN (SELECT BSE.IBLOCK_SECTION_ID
		FROM b_iblock_section_element BSE
		INNER JOIN b_iblock_section BSubS ON BSE.IBLOCK_SECTION_ID = BSubS.ID
		INNER JOIN b_iblock_section BS ON (BSubS.IBLOCK_ID=BS.IBLOCK_ID
			AND BSubS.LEFT_MARGIN>=BS.LEFT_MARGIN
			AND BSubS.RIGHT_MARGIN<=BS.RIGHT_MARGIN)
		WHERE BS.ID IN (3) AND BSubS.ID NOT IN (10))
	AND b_iblock_element.ID=b_sm_product.PRODUCT_ID;

INSERT INTO b_sm_product (PRODUCT_ID, DNC_TYPE_CODE)
SELECT ID as PRODUCT_ID, 3 as DNC_TYPE_CODE
FROM b_iblock_element
WHERE 
	IBLOCK_SECTION_ID IN (SELECT BSE.IBLOCK_SECTION_ID
		FROM b_iblock_section_element BSE
		INNER JOIN b_iblock_section BSubS ON BSE.IBLOCK_SECTION_ID = BSubS.ID
		INNER JOIN b_iblock_section BS ON (BSubS.IBLOCK_ID=BS.IBLOCK_ID
			AND BSubS.LEFT_MARGIN>=BS.LEFT_MARGIN
			AND BSubS.RIGHT_MARGIN<=BS.RIGHT_MARGIN)
		WHERE BS.ID IN (3) AND BSubS.ID NOT IN (10))
	AND ID NOT IN (SELECT b_sm_product.PRODUCT_ID FROM b_sm_product);

INSERT INTO b_sm_product (PRODUCT_ID, DNC_TYPE_CODE)
SELECT ID as PRODUCT_ID, 2 as DNC_TYPE_CODE
FROM b_iblock_element
WHERE 
	IBLOCK_SECTION_ID IN (SELECT BSE.IBLOCK_SECTION_ID
		FROM b_iblock_section_element BSE
		INNER JOIN b_iblock_section BSubS ON BSE.IBLOCK_SECTION_ID = BSubS.ID
		INNER JOIN b_iblock_section BS ON (BSubS.IBLOCK_ID=BS.IBLOCK_ID
			AND BSubS.LEFT_MARGIN>=BS.LEFT_MARGIN
			AND BSubS.RIGHT_MARGIN<=BS.RIGHT_MARGIN)
		WHERE BS.ID IN (3) AND BSubS.ID IN (10))
	AND ID NOT IN (SELECT b_sm_product.PRODUCT_ID FROM b_sm_product);

INSERT INTO `b_sm_dnc_updated_products` (`PRODUCT_ID`, `STORE_ID`)
	SELECT `PRODUCT_ID` , `STORE_ID` FROM `b_catalog_store_product` GROUP BY `PRODUCT_ID` , `STORE_ID`